/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminBooksRouteImport } from './routes/admin.books'
import { Route as AdminBearersRouteImport } from './routes/admin.bearers'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminActivitiesRouteImport } from './routes/admin.activities'

const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBearersRoute = AdminBearersRouteImport.update({
  id: '/bearers',
  path: '/bearers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/library': typeof LibraryRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bearers': typeof AdminBearersRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/home': typeof AdminHomeRoute
  '/events/$id': typeof EventsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/library': typeof LibraryRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bearers': typeof AdminBearersRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/home': typeof AdminHomeRoute
  '/events/$id': typeof EventsIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/library': typeof LibraryRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bearers': typeof AdminBearersRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/home': typeof AdminHomeRoute
  '/events/$id': typeof EventsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/admin'
    | '/announcements'
    | '/contact'
    | '/events'
    | '/library'
    | '/admin/activities'
    | '/admin/announcements'
    | '/admin/bearers'
    | '/admin/books'
    | '/admin/contact'
    | '/admin/events'
    | '/admin/home'
    | '/events/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/announcements'
    | '/contact'
    | '/events'
    | '/library'
    | '/admin/activities'
    | '/admin/announcements'
    | '/admin/bearers'
    | '/admin/books'
    | '/admin/contact'
    | '/admin/events'
    | '/admin/home'
    | '/events/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/admin'
    | '/announcements'
    | '/contact'
    | '/events'
    | '/library'
    | '/admin/activities'
    | '/admin/announcements'
    | '/admin/bearers'
    | '/admin/books'
    | '/admin/contact'
    | '/admin/events'
    | '/admin/home'
    | '/events/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  LibraryRoute: typeof LibraryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bearers': {
      id: '/admin/bearers'
      path: '/bearers'
      fullPath: '/admin/bearers'
      preLoaderRoute: typeof AdminBearersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminBearersRoute: typeof AdminBearersRoute
  AdminBooksRoute: typeof AdminBooksRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminBearersRoute: AdminBearersRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminContactRoute: AdminContactRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  LibraryRoute: LibraryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
